### ISSUE TITLE
make sure modernizr is set up to check for touch events

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#1]

**Comment by jjelosua** [comment]
Modernizr is on the page, let me know if we need to do more testing to mark this as done
<img width="445" alt="screenshot 2017-04-24 17 41 51" src="https://cloud.githubusercontent.com/assets/1834051/25359977/5011ff0e-2915-11e7-8214-b2155de0a6c6.png">

**Comment by jjelosua** [comment]
Fixed by using the new `Modernizr.touchevents` and updated to the latest Modernizr build including video and touchevents detection
