### ISSUE TITLE
discuss the structure of text and images in the intro

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#10]
katie will meet with stephanie to talk through the order and content of the intro section. We think it will need to be more structured than text in an episode.

We have talked about sharing text in a sequence like the Tampa Bay and Highline examples. 

is the transition between the intro and episode scroll based (probably) or click based.

**Comment by katiepark** [comment]
Sounds like the intro will likely be mainly photo/design-driven, not a lot going on graphics-wise. It's possible that when we introduce characters through the conditional intro, that's a good place for a well-annotated, focused map.

**Comment by katiepark** [comment]
Something to discuss on Monday: how we handle lede visuals/titles for the project vs. individual episodes. I did a bit of thinking on this and have a proposal, but we should talk through it.

**Comment by lindamood** [comment]
@katiepark Is it possible to add a link to your proposed approach here and add it to our project folder?
