### ISSUE TITLE
iOS 9 autoplay

### ISSUE THREAD

**Issue by jjelosua** [nprapps/idp-georgia#101]
After testing on an iPad with iOS 9, background videos will not autoplay it looks like this is indeed the expected behavior per:
![screenshot 2017-05-03 17 50 09](https://cloud.githubusercontent.com/assets/1834051/25683246/45c10160-3029-11e7-85b7-d61212b9afa9.png)

Only a user interaction will allow the video to start playing... should we fallback to image as we are doing now or should we think of a better solution?

**Comment by eads** [comment]
This is true for all iOS versions < 10 -- the very possibility of autoplaying video on iOS devices without a gesture only became possible last fall. iOS 10 adoption [seems strong](https://www.macrumors.com/2017/02/22/ios-10-nearly-80-percent-adoption/), however, which makes me think a fallback image is a pretty good option.

**Comment by jjelosua** [comment]
Yeah, I agree I have tested the fallback image option using the poster for the video tag and it seems to work fine on the iPad with iOS 9. so I am going to assume that this is our preferred solution for devices not supporting the new playsinline non-user generated activation. Closing for now
