### ISSUE TITLE
Problems with HLS stream on IE11

### ISSUE THREAD

**Issue by jjelosua** [nprapps/idp-georgia#102]
No playable sources found....investigating

**Comment by jjelosua** [comment]
Testing on Windows 10 and Edge works fine...

**Comment by lindamood** [comment]
waiting to hear back from P. If we don't hear from him, borrow a laptop from DM with IE11 on it.

**Comment by jjelosua** [comment]
Found the solution to this, IE11 only supports MPEG inside the HTML5 video tag so it falls back to a flash player for our needs and the flash loader and player was not included in our code that is why it failed. Added the flash loader and player to our assets and tested on a VirtualMachine it works as expected
