### ISSUE TITLE
When Viewing an interview video should we stop it once it leaves the viewport?

### ISSUE THREAD

**Issue by jjelosua** [nprapps/idp-georgia#103]
@lindamood @katiepark What do you think?
* Leaving if playing could be an option but it seems a bit off, I think stoping it and making the user play it again is a better option....

**Comment by katiepark** [comment]
I think that makes sense. Maybe a pause or a mute instead of a full stop? But yeah, probably good to turn off the sound at the very least.

**Comment by jjelosua** [comment]
I think pausing is better than muting since the return to the viewport will require user interaction to start the video again, if we mute then maybe we should unmute going back to the viewport and that may seem confusing IMO is the video has continued to play and you go back to a different place of the interview

**Comment by jjelosua** [comment]
@lindamood do you agree that pausing the video interviews when exiting the viewport is the right solution? That's how it is implemented on `master` for example with Ana video interview....let me know your thoughts, I think it is the best UX but up for discussion.

**Comment by lindamood** [comment]
@jjelosua yes. I agree.

**Comment by jjelosua** [comment]
Since that is already implemented I am closing this one
