### ISSUE TITLE
iOS Chrome bug: content jumping up/down when browser chrome shows/hides

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#138]
can we:

- always show the browser chrome
- take the intro out of the flow of the document when user has scrolled passed the intro
- lock the size of the intro panels to the size of the viewport when the browser chrome is visible

**Comment by lindamood** [comment]
https://www.reddit.com/r/web_design/comments/3eurig/anyone_implemented_vh_background_images_and/

**Comment by lindamood** [comment]
http://stackoverflow.com/questions/24944925/background-image-jumps-when-address-bar-hides-ios-android-mobile-chrome

**Comment by lindamood** [comment]
@jjelosua I pushed a fix out on this branch for the scroll bug:
https://github.com/nprapps/idp-georgia/tree/chrome-chrome-fix

Strangely, it causes the title card video to disappear and not return once you scroll past it.

**Comment by jjelosua** [comment]
Addressed through javascript here: d25f211, orientation change is not perfect but it is better than the initial situation
