### ISSUE TITLE
Create looping video promo for the HP

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#144]

**Comment by lindamood** [comment]
@jjelosua Katie is out sick today. The plan is to embed an HTML asset on the home, and provide Steve with instructions for how to add the asset to the home page. We'd like to use the Kartli video. Do we have an optimized version of that video? We can check and see if Aly and Tyler can provide an assist on this task.

![georgia-reserach__canvas_8](https://cloud.githubusercontent.com/assets/1319852/26452788/3a41bd72-412f-11e7-9435-14381ab094a4.png)

**Comment by jjelosua** [comment]
I have created a video loop graphic inside dailygraphics for the Homepage to use...I have added it to the shell page (id: 529180546) and moved it to the drawer....we need to add language on the Launch doc to signal this option to the Homepage team.... @lindamood can you do that?

**Comment by jjelosua** [comment]
Regarding this I would like to check with HP where are they planning to use it and in what size....since depending on the use of if we could point out to different versions of the video with lower weight...

**Comment by jjelosua** [comment]
Added some tweaking of the video quality/size/weight based on the initial containerWidth. May need to review it after I understand better the different formats we get back from DMP when a video is transcoded.

**Comment by jjelosua** [comment]
Need to test with homepage on staging today, Let's try to move that quickly to get it out of the way.

**Comment by jjelosua** [comment]
Tested on staging and working fine, added the embed code to the launch doc.
