### ISSUE TITLE
Episodes will need to detect whether user has already viewed intro

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#5]

**Comment by lindamood** [comment]
Intro should be session based. the only context in which you do not see the intro is when moving between episodes.

**Comment by jjelosua** [comment]
Addressed here #567f70c

**Comment by jjelosua** [comment]
We use sessionStorage for the intro conditional logic and remove the conditional treatment of footers since we want the user to always see the same footer for each episode
