### ISSUE TITLE
Video options

### ISSUE THREAD

**Issue by jjelosua** [nprapps/idp-georgia#62]
From @eads:
I hear video is a question on this, but didn't see a ticket. I have some thoughts about options that I think could work, though they are by no means definitive:

* Cloudfront + HLS + customized JWplayer: https://www.jwplayer.com/blog/delivering-hls-with-amazon-cloudfront/ -- NPR pays for the commercial version of JW Player, so I believe it would be possible to self-host completely. A minor downside is there will be a variable cost based on how much data is delivered. Another downside is even if we move the apps.npr.org cloudfront distribution to akamai, we'd still need to maintain the video hosting distribution for this one special project.

* NPR's media hosting + customized JWplayer: I suspect this is the cleanest option, but not the easiest to implement. We already have a bunch of infrastructure to do this at NPR but outside Visuals; the question here is how difficult making a customized, basically chromeless JW player would be (also an issue for the previous option) and how much effort all the coordination to make it happen would be.

* Vimeo Pro offers chrome-less embedding, autoplay, and looping. It costs money and Ariel mentioned there's the issue of having a bunch of 10 second clips littered among more substantive content on the vimeo site itself. It creates a dependency on Vimeo. But it's also very easy to do -- this has gotta be one of the lowest effort options.

* Canvid: you could dynamically load a specific canvid sprite based on screen size. I don't think this is a better option than any kind of HTML5 video option now that IOS supports autoplay for video tags, we can stream pretty readily from our infrastructure, etc.

**Comment by eads** [comment]
fwiw the more I think about it the more I think the NPR streaming infrastructure + a lean and mean JWPlayer feels to me like the best solution

**Comment by jjelosua** [comment]
Talking with Patrick in order to see if getting a fresh JWplayer for our needs is possible with our current commercial agreement with them

**Comment by jjelosua** [comment]
Ok, regarding video options we can choose one of two roads AFAIU, if we are going to use HLS stream we will need a JS player that supports that and that uses the latest iOS and Android autoplay capabilities. 
- `Clappr`: does not use the new video tag params and thus does not autoplay. 
- `JWPlayer`: does play on mobile and supports HLS but there will be some cost involved, since we are charged per number of plays

If we are not going to use HLS streams, then we might go directly to standard HMTL video tags with the mp4s that production can transcode for us. Drawbacks: we will not have the capability to adapt the Quality of the video to the size of the device and bandwidth of the user connection resulting on a higher data consumption & slower app.

**Comment by jjelosua** [comment]
After talking through our options it seems that HLS streaming is not suited for our short background videos so we can use straight HTML5 video tags for those. For the interviews HLS may be better to use the JWPlayer adaptive streaming feature. Right now this is the approach we have taken on the prototype for Ana story (the only one including a video interview for now)

**Comment by jjelosua** [comment]
After talking with onlineproduction it seems that having an HLS stream for the interview videos is a viable option so if we figure out what is going on on IE11 we could close this one.

**Comment by jjelosua** [comment]
HLS issue on IE11 is solved, talking with patrick about billing options but the road is clear so I am closing this one.
