### ISSUE TITLE
Make the conditional intro for Irakli feel more like the start of a story

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#67]
Right now it feels more like the end of the intro. Consider using more panels/slides in the conditional intro section to cover the key points we want to cover.

- Explore paragraphs in the conditional intro instead of headlines/subheads
- introduce the character for the episode in the conditional header.

**Comment by lindamood** [comment]
explore ways that users can view the season intro again. is it a click or a scroll like highline back up.

**Comment by katiepark** [comment]
addressed in a few ways, primarily a345343680d6748878d5dffaa2dccad4974da87a and 1d752f3f049018cf5524839920d1f107e4ad61fe
