### ISSUE TITLE
Irakli episode footer design

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#68]
consider:

- utility navigation between episodes. make it clear that there are multiple episodes in the season.
- footer design that emphasizes the next episode. 
- take a pass at the flow from the end of the Irakli episode into the intro of the Ana episode. What lives in the Irakli footer? What lives in the Ana intro?

**Comment by katiepark** [comment]
Sketch for episode footer:
![image](https://cloud.githubusercontent.com/assets/969843/25361633/65d2e2ec-291d-11e7-93dd-d205ee443719.png)

Sketch for series ender:
![image](https://cloud.githubusercontent.com/assets/969843/25361643/7591d7e2-291d-11e7-867b-e43d1004a970.png)
