### ISSUE TITLE
Prototype a jinja include approach to photo grids and other asset layouts in the flow of a story

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#70]
if we use an approach more than once, convert the template into google doc template code.

**Comment by lindamood** [comment]
let's wait until we have a situation complex enough that we need this approach.

**Comment by jjelosua** [comment]
The lift to do custom shortcodes -> jinja templates -> injection of custom html to an episode it is pretty straightforward and that would leave as with the google doc being a more realistic container of the story text for our purposes. For example:

![screenshot 2017-04-24 17 47 52](https://cloud.githubusercontent.com/assets/1834051/25360292/86a5f790-2916-11e7-974b-ab3adb4a5214.png)

https://github.com/nprapps/idp-georgia/blob/master/templates/shortcodes/video.html

<img width="934" alt="screenshot 2017-04-24 17 49 54" src="https://cloud.githubusercontent.com/assets/1834051/25360286/7fd2517a-2916-11e7-959e-2935253568e0.png">

**Comment by jjelosua** [comment]
I think we can close this one, since our needs our covered for now
