### ISSUE TITLE
mobile: do background videos play as expected?

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#71]
see #62 

and

Starting in iOS 10, WebKit relaxes its inline and autoplay policies to make these presentations possible, but still keeps in mind sites’ bandwidth and users’ batteries.
https://webkit.org/blog/6784/new-video-policies-for-ios/

**Comment by jjelosua** [comment]
Using playsinline autoplay muted on iphone and tested it out....need to find an old iphone to check fallbacks

**Comment by jjelosua** [comment]
When adding multiple videos to the page short background& long interview ones, if the long interview comes before a short background one, it seems to block the playback for the later, If on the contrary I fully load the interview video then the posterior background video performs as expected.

some tests done on this document: https://docs.google.com/document/d/1pEeOxqc3ruy8Cy8IksZOMpnr_gTHIlx62praiyJX2vk/edit

**Comment by jjelosua** [comment]
It seems that the issue is only happening locally, I think that it might be related with the python local server not being able to handle multiple requests for heavy assets. After deploying to staging the issue was solved on its own....keep digging though

**Comment by jjelosua** [comment]
Background videos work as expected tested on Android, iPad iOS 10, iPhone iOS 10, Chrome, Safari, Firefox and IE11
