### ISSUE TITLE
utility nav: clearly communicate what episode you are currently in.

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#72]

**Comment by jjelosua** [comment]
@lindamood I have added a class to the body that reflects the current episode you are viewing to allow for various highlighting options to indicate the episode you are in
![screenshot 2017-04-24 17 38 37](https://cloud.githubusercontent.com/assets/1834051/25359911/10fbb2e2-2915-11e7-8fb9-317a68ebf9ad.png)
