### ISSUE TITLE
list places where graphics might live in each episode

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#75]
for example:

- locator map of irakli’s old home vs. new home.
- possibly chart survey data on housing.

**Comment by katiepark** [comment]
Went back through the drafts and made this list:

Irakli
- Map of hometown in Sokhumi and path to current home
- Not immediately relevant: Survey data on IDP desire to return voluntarily
- Not immediately relevant: IDP numbers in Georgia, worldwide, refugee numbers? A place early on to re-state the definition of an IDP?

Ana
- Map of path from Tskhinvali -> Gori -> Tbilisi -> Berbuki
- Small unemployment chart?

Veriko
- Map of Gali/Zugdidi and Abkhazia boundary

The story does not really address a bigger/data-driven IDP story, but I'm wondering if a graphic would actually provide that angle and remind readers of the definition of an IDP. It might not work in all three drafts -- was primarily thinking through Irakli's.
