### ISSUE TITLE
lazy loading of assets 

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#8]

**Comment by jjelosua** [comment]
Reuse some of the work done on the liveblog to identify aspect ratios to generate placeholders and scroll tracking to lazy load assets adapting it to our functionality, Should we lazy load assets on partial visibility or prerender the next asset also even though is not yet on view?

**Comment by jjelosua** [comment]
@lindamood @katiepark Should we lazy load assets individually when they become visible on the viewport or should we use a container approach to lazyload all assets inside them? for example lazyload all assets for each visible section?

**Comment by katiepark** [comment]
I think it would be good to prerender assets before they come into view. Not sure if I have a strong opinion about containers or individual assets... When you say "section," do you mean sections within each story?

**Comment by eads** [comment]
Loading before they become visible is always a good idea. For the liveblog we loaded several ahead of what would be visible on a normal viewport.

Also worth noting that with HTTP/2 (which cloudfront now supports and all the major browsers do provided you're also using https) loading several assets in a single shot doesn't require overhead of multiple connections. I haven't read up on how it affects lazy loading strategies but I'd imagine loading several assets at a time is a fairly optimal approach.

**Comment by jjelosua** [comment]
Yeah I mean sections within an episode...let me try with a section approach and let's move from there

**Comment by jjelosua** [comment]
We will use the section based approach to lazy load assets
