### ISSUE TITLE
Sticky nav design

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#86]

**Comment by jjelosua** [comment]
Done here: 97c0802

**Comment by jjelosua** [comment]
@lindamood left a hooked up working solution on https://github.com/nprapps/idp-georgia/tree/sticky-nav that needs some more design work but it is functional

**Comment by lindamood** [comment]
the styling of the sticky nav banner is in place. I'll style the nav after we decide on an mobile approach.

**Comment by lindamood** [comment]
- show menu on tap/click
- take WaPo approach to nav. a semi-transparent modal over the whole viewport instead of a traditional dropdown.
- can do it as a checkbox like this: http://www.npr.org/2016/11/08/500927768/2016-presidential-election-results-for-each-state or in JS
- check for weird wrapping issues on menu titles across breakpoints.

**Comment by jjelosua** [comment]
The breakpoints issue is not solved but having a mobile click functionality is.
