### ISSUE TITLE
Ask DM about sitemap for apps.npr.org integration... indexing etc...

### ISSUE THREAD

**Issue by lindamood** [nprapps/idp-georgia#9]

**Comment by jjelosua** [comment]
From Patrick:

`After doing a little research, our existing sitemap appears to be very tied to Seamus publishing and the Seamus database. Add the fact that no one’s made major changes to the map generation process in years, and we’re looking at a not-easy route to incorporating non-Seamus content.

BUT there does appear to be a much easier route. In Google’s webmaster toolset, I can submit multiple sitemaps for NPR.org. We already produce a separate sitemap for Google News. So, if Viz wanted to create a map for apps.npr.org, it would take me all of two minutes to add.``

It seems that we would need to generate our own `apps.npr.org` sitemap and pass it along to Patrick to be included under NPR.org. We would need to filter only standalone projects and update each time we create a new one....

I am waiting on Patrick response about the specific format he wants...will then generate an inventory of projects inside apps.npr.org and then pass it along to the team to help identify standalone projects that we feel that should be included.

**Comment by jjelosua** [comment]
Don
